trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: CmdLine@2
  inputs:
    script: |
      git clone https://github.com/rdagumampan/yuniql $(Build.SourcesDirectory)\yuniql

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.201'

- task: CmdLine@2
  inputs:
    script: |
      dotnet tool install -g yuniql.cli
      #yuniql version

- task: CmdLine@2
  inputs:
    script: |
      yuniql erase -c "$(PostgreSqlDemoDatabase)" -p "$(Build.SourcesDirectory)\yuniql\samples\basic-postgresql-sample" --platform postgresql --debug

- task: CmdLine@2
  inputs:
    script: |
      yuniql run -c "$(PostgreSqlDemoDatabase)" -p "$(Build.SourcesDirectory)\yuniql\samples\basic-postgresql-sample" --platform postgresql --debug