trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: CmdLine@2
  displayName: clone postgresql samples repo
  inputs:
    script: |
      git clone https://github.com/rdagumampan/yuniql $(Build.SourcesDirectory)\yuniql

- task: CmdLine@2
  displayName: choco install yuniql
  inputs:
    script: |
      choco install yuniql

- task: CmdLine@2
  displayName: yuniql erase
  inputs:
    script: |
      yuniql erase -c "$(PostgreSqlDemoDatabase)" -p "$(Build.SourcesDirectory)\yuniql\samples\basic-postgresql-sample" --platform postgresql --debug

- task: CmdLine@2
  displayName: yuniql run
  inputs:
    script: |
      yuniql run -c "$(PostgreSqlDemoDatabase)" -p "$(Build.SourcesDirectory)\yuniql\samples\basic-postgresql-sample" --platform postgresql --debug