trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: CmdLine@2
  displayName: clone postgresql samples repo
  inputs:
    script: |
      git clone https://github.com/rdagumampan/yuniql $(Build.SourcesDirectory)\yuniql

- task: UseYUNIQLCLI@0
  displayName: yuniql install
  inputs:
    version: 'latest'

- task: EraseYuniqlCLI@0
  displayName: yuniql erase
  inputs:
    version: 'latest'
    connectionString: '$(AwsPostgreSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)\yuniql\samples\basic-postgresql-sample'
    targetPlatform: 'postgresql'
    additionalArguments: '--debug'

- task: RunYUNIQLCLI@0
  displayName: yuniql run
  inputs:
    version: 'latest'
    connectionString: '$(AwsPostgreSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)\yuniql\samples\basic-postgresql-sample'
    targetPlatform: 'PostgreSql'
    additionalArguments: '--debug'
