trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  displayName: clone postgresql samples repo
  inputs:
    script: |
      git clone https://github.com/rdagumampan/yuniql $(Build.SourcesDirectory)/yuniql

- task: UseDotNet@2
  displayName: dotnet sdk install v3.1.201
  inputs:
    packageType: 'sdk'
    version: '3.1.201'

- task: CmdLine@2
  displayName: dotnet tool install -g yuniql.cli
  inputs:
    script: |
      dotnet tool install -g yuniql.cli
      export PATH=$HOME/.dotnet/tools:$PATH

- task: CmdLine@2
  displayName: yuniql erase
  inputs:
    script: |
      yuniql erase -c "$(AwsPostgreSqlDemoDatabase)" -p "$(Build.SourcesDirectory)/yuniql/samples/basic-postgresql-sample" --platform postgresql --force --debug

- task: CmdLine@2
  displayName: yuniql run
  inputs:
    script: |
      yuniql run -c "$(AwsPostgreSqlDemoDatabase)" -p "$(Build.SourcesDirectory)/yuniql/samples/basic-postgresql-sample" --platform postgresql --debug
